### ISSUE TITLE
finalize first version of speaker-details page and speaker-list component

### ISSUE THREAD

**Issue by usefulthink** [cssconf/2017.cssconf.eu#52] opened 2017-01-20 22:36 UTC

**Comment by Kriesse** [comment] 2017-01-25 00:01
@usefulthink 

I added a speaker list component, and three test speaker files with generic content (no more del Rey).
The component is included on the homepage, on /speakers, and on single speaker pages.
The corresponding styles are [here](https://github.com/cssconf/2017-assets/pull/13). 

## Notes

* Each speaker now has `color` and `bg`, as the mockup specifies varying colors for both text and background. As the text-color is often white, the color for the header title on a single speaker page now uses the `bg` color (as white would be not visible on the light header background).

* I am seeing a weird broken page with unescaped text (?) when I open a single speaker page. Not exactly sure how to reproduce. Opening the page again in a new tab sometimes fixes it. 
![image](https://cloud.githubusercontent.com/assets/53684/22272253/e85f29f8-e24d-11e6-8380-89b58a278e45.png)


## Preview: Desktop
![image](https://cloud.githubusercontent.com/assets/53684/22272112/2f749ba8-e24d-11e6-9de1-42af0dfc5ba6.png)

## Preview: Mobile
![image](https://cloud.githubusercontent.com/assets/53684/22272186/757d2732-e24d-11e6-9096-180355160a8e.png)

**Comment by RalloTubbs** [comment] 2017-02-22 07:43
details visual feedback:

- shadow behing Una looks cut
<img width="448" alt="screenshot 2017-02-22 08 40 14" src="https://cloud.githubusercontent.com/assets/7797904/23201603/96e3d030-f8da-11e6-8405-d5efe0f9fc72.png">

- boxes could be higher, because in balance to the other elements they look small, we don't have to make it that high, maybe 20 higher would help, if the fontsize stays like this
- boxes always left aligned: we could always add a next box saying tba
<img width="517" alt="screenshot 2017-02-22 08 34 55" src="https://cloud.githubusercontent.com/assets/7797904/23201450/eace2746-f8d9-11e6-9840-1c74c21a40d4.png">
- still the names could be bigger?

- the box on detailpage could have more meat like this
<img width="606" alt="screenshot 2017-02-22 08 39 01" src="https://cloud.githubusercontent.com/assets/7797904/23201615/9f159db0-f8da-11e6-87c9-1bb52c9e03a3.png">

**Comment by lukaszklis** [comment] 2017-02-22 12:43
@RalloTubbs if you don’t mind, I’d like to close this issue and create a new ones.

**Closed as completed by lukaszklis** 2017-02-22 12:43 UTC

**Comment by lukaszklis** [comment] 2017-02-22 12:55
Split into #59, #60, #61

**Comment by RalloTubbs** [comment] 2017-02-22 12:57
@lukaszklis please do
